Update Mesh API to allow implementation of Limited Trust
cisco-app-networking/service-mesh-hub pull request #1
Opened 2020-09-29 14:42 UTC by mihmatache

- Added the Egress Gateway object to the Mesh API.

- Added HTTPS port to the existing Ingress Gateway

This change will allow multiple people to continue to work on implementing limited trust, as this is the main cross dependency.

Follow up PR will be created for:
- Creating the different objects that are needed in Istio to implement Limited trust
- Creating the Secrets that will be used for the mTLS between the gateways

2020-09-29 14:51 UTC, danielvladco requested changes

2020-09-29 14:51 UTC, danielvladco commented on pkg/mesh-discovery/translation/mesh/detector/istio/istio_mesh_detector.go
> +		HttpsContainerPort: unit32(httpsContainerPort),
```suggestion
		HttpsContainerPort: uint32(httpsContainerPort),
```

2020-10-29 19:29 UTC, 91pavan commented on pkg/mesh-discovery/translation/mesh/detector/istio/istio_mesh_detector.go
> +		port := port // pike
Is this re-initialization needed?

2020-10-29 19:38 UTC, 91pavan commented on api/networking/v1alpha2/virtual_mesh.proto
> +            RootCertificateAuthority root_certificate_authority = 1;
I'd probably remove the comment and the root ca(!?) since SMH is brokering the mTLS b/w egress and ingress gateway traffic and acting as a neutral agent. If we do allow a root ca to be supplied, it would need to be different from the Root CA of underlying meshes right.

2020-10-29 19:40 UTC, 91pavan commented on docs/content/reference/api/mesh.md
> +| httpsPort | uint32 |  |  |
add missing description: https defaults to 443 port

2020-10-29 19:41 UTC, 91pavan commented on pkg/common/defaults/istio.go
> +	// their ingress gateway is hardcoded in their own implementation to have this label
```suggestion
	// their egress gateway is hardcoded in their own implementation to have this label
```

2020-10-29 19:51 UTC, 91pavan commented on pkg/mesh-networking/translation/istio/mesh/mtls/mtls_translator.go
> +	istioCaCerts.Name = defaultCaSecretName
Is this being used for limited trust?

2020-10-30 06:46 UTC, mihmatache commented on pkg/mesh-discovery/translation/mesh/detector/istio/istio_mesh_detector.go
> +		port := port // pike
Probably not (since this is not starting a in a go routine), but they do have throughout their code (this is basically moving an in code logic to a function), so I decided to keep it, just in case I'm missing any information.

2020-10-30 06:58 UTC, mihmatache commented on api/networking/v1alpha2/virtual_mesh.proto
> +            RootCertificateAuthority root_certificate_authority = 1;
Not necessarily. 
The logic for limited trust is, when I receive a Root CA, I go ahead and configure intermediate certificates from the Root CA. I don't really care where the initial Root CA comes from (generated or provided). That being said, the comment there is bad, I will change it.

2020-10-30 07:03 UTC, mihmatache commented on pkg/mesh-networking/translation/istio/mesh/mtls/mtls_translator.go
> +	istioCaCerts.Name = defaultCaSecretName
No, copy paste error. Will remove.

2020-10-30 11:26 UTC, 91pavan approved these changes
Looks good!

2020-11-02 18:15 UTC, john-a-joyce reviewed
A minor comment on the port range allowed - otherwise looks LGTM with the caveat that I not expert enough on the SMH code to review some of the more complex logic.

2020-11-03 09:47 UTC, mihmatache commented on install/helm/service-mesh-hub/crds/discovery.smh.solo.io_v1alpha2_crds.yaml
> +                        maximum: 4294967295
This part of the code is autogenerated by the SMH SKV2 code. I don't have any powers over this. But I will note it down to bring it up with them at the next community meeting.

2020-11-03 16:17 UTC, merged